env: "local"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
database_server:
  ip: "127.0.0.1"
  port: 5432
  database: "shorturl"
  user: "shorturl"
  password: "shorturl"
random_alias_length: 6